config/routes.rb
Rails.application.routes.draw do
  get 'documentary_films/index'
  get 'documentary_films/new'
  get 'series/index'
  get 'series/new'
  get 'movies/index'
  get 'movies/new'
  

  post "/movies/create" => "movies#create"
  post "/series/create" => "series#create"
  post "/documentary_films/create" => "documentary_films#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_films = DocumentaryFilm.all
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_films_params)
    if @documentary_film.save
      redirect_to documentary_films_index_path
    else 
      render :new
    end
  
  end

  def documentary_films_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movies_params)
    if @movie.save
      redirect_to movies_index_path
    else 
      render :new
    end
  end

  def movies_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
  
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.all
  end

  def new
    @serie = Serie.new
  end

  def create
    @serie = Serie.new(series_params)
    if @serie.save
      redirect_to series_index_path
    else 
      render :new
    end
  end

  def series_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/create.html.erb
<h1>DocumentaryFilms#create</h1>
<p>Find me in app/views/documentary_films/create.html.erb</p>

app/views/documentary_films/index.html.erb
<div> 
  <h1>Listado de Documentales</h1>
</div>
<br>

<%= link_to 'Ingresar un nuevo Documental', documentary_films_new_path %>
<br>
<br>
<div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nombre del Documental</th>
        <th scope="col">Sinopsis</th>
        <th scope="col">Director</th>
      </tr>
    </thead>
    <tbody>
      <% @documentary_films.each do |documentary_film| %>
      <tr>
        <th scope="row"><%= documentary_film.id %></th>
        <td><%= documentary_film.name %></>
        <td><%= documentary_film.synopsis %></td>
        <td><%= documentary_film.director %></td>
      </tr>
      <% end %>
    </tbody>
  </table> 

</div>

app/views/documentary_films/new.html.erb
<h1>Registro de Documentales</h1>

<%= form_with url:'/documentary_films/create', model: @documentary_film, method: :post do |form|%>

    <div>
        <%= form.label :name, "Nombre del Documental"%> <br>
        <%= form.text_field :name %> 
    </div> <br>
    <div>
        <%= form.label :synopsis, "Sinopsis" %> <br>
        <%= form.text_area :synopsis %> 
    </div><br>
    <div>
        <%= form.label :director, "Director" %> <br>
        <%= form.text_field :director %>  
    </div><br>
    <div>
        <%= form.submit "Guardar Documental"%> <br>
    </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio3Franciscaolivares</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container text-center">
      <%= yield %>
    </div>
     
    
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<div> 
  <h1>Listado de Peliculas</h1>
</div>
<br>

<%= link_to 'Ingresar una nueva película', movies_new_path %>
<br>
<br>
<div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col">N°</th>
        <th scope="col">Nombre de la Pelicula</th>
        <th scope="col">Sinopsis</th>
        <th scope="col">Director</th>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
      <tr>
        <th scope="row"><%= movie.id %></th>
        <td><%= movie.name %></>
        <td><%= movie.synopsis %></td>
        <td><%= movie.director %></td>
      </tr>
      <% end %>
    </tbody>
  </table> 

</div>

app/views/movies/new.html.erb
<h1>Registro de Peliculas</h1>

<%= form_with url: '/movies/create', model: @movie, method: :post do |form|%>

    <div>
        <%= form.label :name, "Nombre de la pelicula"  %> <br>
        <%= form.text_field :name %> 
    </div><br>
    <div>
        <%= form.label :synopsis, "Sinopsis" %> <br>
        <%= form.text_area :synopsis %> 
    </div><br>
    <div>
        <%= form.label :director, "Director" %> <br>
        <%= form.text_field :director %>  
    </div><br>
    <div>
        <%= form.submit "Guardar Pelicula"%>
    </div>

<% end %>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<div> 
    <h1>Listado de Series</h1>
  </div>
  <br>
  
  <%= link_to 'Ingresar una nueva Serie', series_new_path %>
  <br>
  <br>  
  <div>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th scope="col">N°</th>
          <th scope="col">Nombre de la Serie</th>
          <th scope="col">Sinopsis</th>
          <th scope="col">Director</th>
        </tr>
      </thead>
      <tbody>
        <% @series.each do |serie| %>
        <tr>
          <th scope="row"><%= serie.id %></th>
          <td><%= serie.name %></>
          <td><%= serie.synopsis %></td>
          <td><%= serie.director %></td>
        </tr>
        <% end %>
      </tbody>
    </table> 
  
  </div>
  
  
  

app/views/series/new.html.erb
<h1>Registro de Series</h1>

<%= form_with url: '/series/create', model: @serie, method: :post do |form|%>

    <div>
        <%= form.label :name, "Nombre de la Serie"  %> <br>
        <%= form.text_field :name %> 
    </div><br>
    <div>
        <%= form.label :synopsis, "Sinopsis" %> <br>
        <%= form.text_area :synopsis %> 
    </div><br>
    <div>
        <%= form.label :director, "Director" %> <br>
        <%= form.text_field :director %>  
    </div><br>
    <div>
        <%= form.submit "Guardar Serie"%>
    </div>

<% end %>